plugins {
    id 'java'
    id 'maven-publish'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'vren'
version = '1.0.2.001-release'


dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
tasks.withType(JavaExec).configureEach {
    jvmArgs += ["-Dfile.encoding=UTF-8", "-Dstdout.encoding=UTF-8", "-Dstderr.encoding=UTF-8"]
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
}

test {
    useJUnitPlatform()
}