plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'org.vren'
version = '1.0-ALPHA'

repositories {
    mavenCentral()
}


dependencies {
    implementation 'org.openjfx:javafx-controls:21'
    implementation 'org.openjfx:javafx-fxml:21'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

javafx {
   version = "21"
   modules = [ 'javafx.controls', 'javafx.fxml' ]
}

tasks.withType(JavaExec).configureEach {
    doFirst {
        jvmArgs += ['--module-path', classpath.asPath, '--add-modules', 'javafx.controls,javafx.fxml']
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
tasks.withType(JavaExec) {
    jvmArgs += ["-Dfile.encoding=UTF-8", "-Dstdout.encoding=UTF-8", "-Dstderr.encoding=UTF-8"]
}

test {
    useJUnitPlatform()
}